default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: xben_app_prototype_development

test:
  <<: *default
  database: xben_app_prototype_test

production:
  <<: *default
  database: xben_app_prototype_production
  username:
  password:
