#!/bin/bash

ID='xben-app'
PORT=${1:-3000}


section() {
  printf "\e[33m==> $1\e[0m\n"
}


section "Starting ngrok"
SUBDOMAIN="$ID-$PORT"
ngrok -log=stdout -subdomain=$SUBDOMAIN $PORT > /dev/null &

if [ $? -ne 0 ]; then
  echo "Failed to create tunnel"
  exit 1
fi

NGROK_PID=$!

echo "Tunneling localhost:$PORT --> ${SUBDOMAIN}.ngrok.com"


control_c() {
  section 'Exiting'
  kill -9 $NGROK_PID
  exit $?
}

trap control_c INT


section "Starting rails server at port $PORT"
bundle exec rails s -p $PORT
